services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USER_NAME=test_user
      - USER_PASSWORD=verysecret
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010